application: root-array-523
version: 29
runtime: go
api_version: go1

handlers:
- url: /(.*\.(gif|png|jpg|ico))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|ico)$

- url: /gservice/js/(.*\.js)$
  static_files: mv2/gservice/js/\1
  upload: mv2/gservice/js/.*\.js$

- url: /.*
  script: _go_app
